[package]
name = "automation_tasks_rs"
version = "1.0.0"
authors = ["bestia.dev"]
homepage = "https://bestia.dev"
edition = "2021"
description = "Automation tasks coded in Rust language for the workflow of Rust projects"
publish = false

[dependencies]
cargo_auto_lib = "2.0.6"
# cargo_auto_lib={path="/home/rustdevuser/rustprojects/cargo_auto_lib"}
pretty_dbg = "1.0.54"

