name: rust_fmt_auto_build_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust_fmt_auto_build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Fmt
      run: cargo fmt -- --check
    - name: Install cargo-auto
      run: cargo install cargo-auto
    - name: Build
      run: cargo auto build
    - name: Test
      run: cargo auto test
      
